name: DEV - Build

on:
  workflow_dispatch:
  
  push:
    branches:
      - developor
  pull_request:
    branches:
      - developor

env:
  APP_NAME: phaisci-tutorial-frontend
  CONTAINER_REPOSITORY: "acrphiacitutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  unitest:
    name: UnitTest
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v2